name: packer
"on":
  push: null
env:
  PRODUCT_VERSION: latest
jobs:
  packer:
    runs-on: ubuntu-20.04
    name: Run Packer
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}
    - name: Run `packer init`
      id: init
      run: packer init packer/
    - name: Run `packer fmt`
      id: fmt
      run: packer fmt -check packer/
    - name: Run `packer validate`
      id: validate
      run: packer validate -syntax-only packer/
